### ISSUE TITLE
I can't see dashboard features

### ISSUE THREAD

**Issue by olivierognn** [siegfried415/portia-dashboard#3]
After I lunch:
`sudo docker run -i -t --rm -v <PROJECTS_FOLDER>:/app/data/projects:rw -p 9001:9001 siegfried415/portia-dashboard start-dev`
 
I go to localhost:9001, I create new project, new spiders, but I can't see buttons like "deploy project"

Why?

**Comment by siegfried415** [comment]
Can you give a screenshot when you click ‘...' button  on the right side of project name?

**Comment by olivierognn** [comment]
here is it

http://i64.tinypic.com/2vkhnxk.png

**Comment by olivierognn** [comment]
Do I need to continue with the documentation after I run the docker container ?
or I should already see the button?

**Comment by siegfried415** [comment]
The popup menu was draw by  /app/portiaui/app/templates/components/project-listing.hbs :

> 

                    <li> <a href={{downloadUrl}} target='_blank'>
                        {{list-item-icon class="icon" icon="download"}}Download as Portia
                    </a> </li>
                    <li><a href={{downloadCodeUrl}} target='_blank'>
                        {{list-item-icon class="icon" icon="code"}}Download as Scrapy
                    </a> </li>


                    <li><a {{action (chain-actions (action 'deploy') options.closeMenu) }}>
                        {{list-item-icon class="icon" icon="publish"}} Deploy project
                        </a>
                    </li>

So if you have seen "Download as Portia" and "Download as Scrapy", there is no reason you can't see "Deploy project".  Login in to docker  to  make sure /app/portiaui/app/templates/components/project-listing.hbs has the correct code.

**Comment by olivierognn** [comment]
I can't do that with your instructions 
<a href="http://it.tinypic.com?ref=16hjj3b" target="_blank"><img src="http://i67.tinypic.com/16hjj3b.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by olivierognn** [comment]
Ok Now I'm in, using container's id seems to enter in the docker container, 
as i can see there is the right code:
<img src = "https://imgur.com/a/AJtdP">

**Comment by siegfried415** [comment]
Sorry, I lost `-f` before ancestor，the correct one should be: 

> portia_container_id=\`sudo  docker ps --format {{.ID}} -f ancestor=siegfried415/portia-dashboard\`

**Comment by siegfried415** [comment]
What browser do you use?

**Comment by siegfried415** [comment]
: )

**Comment by olivierognn** [comment]
I have a little question, I didn't find it in the doc: How can I get items from another server with the APIs?
something like this:
https://doc.scrapinghub.com/api/items.html
