### ISSUE TITLE
How I can get items?

### ISSUE THREAD

**Issue by olivierognn** [siegfried415/portia-dashboard#4]
After I run a job I can see the list of items scraped, How can I get these Items like on scrapinghub (with APIs) ? Or where are stored ?

**Comment by olivierognn** [comment]
in the <PROJECTS_FOLDER> i choose there is no items

**Comment by siegfried415** [comment]
Items are stored in mongodb,  look at `article_list` and `article_detail ` at [portia_dashboard/views.py](https://github.com/siegfried415/portia-dashboard/blob/master/portia_server/portia_dashboard/views.py) for reference.

**Comment by olivierognn** [comment]
after 3 hours i can say, I'm not able to get stored Items from DB.
Can you suggest me how I can do that?
There is no way to export csv, json etc file?

**Comment by siegfried415** [comment]
Because portia spider is in fact scrapy spider, so you can write your own scrapy pipeline extension to output items to file in any format you want.
