### ISSUE TITLE
项目运行后报404

### ISSUE THREAD

**Issue by Loni0527** [siegfried415/portia-dashboard#5]
我刚接触python不久，还不太熟，运行环境是win7 python3.7 django2.03
成功运行Portia-dashboard的manage.py后提示404
我的url.py为:
from django.conf.urls import url, include

from . import views
from portia_api import urls

urlpatterns = [
    url(r'^api/', include((urls,'api'), namespace='api')),
    url(r'^server_capabilities$', views.capabilities),
    url(r'^dashboard/', include('portia_dashboard.urls' ))
]
![2](https://user-images.githubusercontent.com/29487688/38007720-5020ffdc-327d-11e8-9130-d393ac06e8d6.png)

请问我该如何配置首页呢？
烦请赐教，不胜感激。

**Comment by siegfried415** [comment]
应该使用9001端口来访问portia-dashboard。

**Comment by Loni0527** [comment]
@siegfried415 感谢您的回复，请问我该如何启动portia-dashboard?
实在是刚接触python，很多地方都还不懂，请见谅，谢谢。

**Comment by siegfried415** [comment]
请参考 [installation.rst ](https://github.com/siegfried415/portia-dashboard/blob/master/docs/installation.rst)中介绍的两种方法，如果你对python不熟悉，建议你用docker来进行体验，会省去很多弯路。

**Comment by Loni0527** [comment]
@siegfried415 十分感谢。
